name: balloon_hashing
description: Balloon Hashing implemented in Dart.
version: 0.0.1
homepage: https://github.com/elliotwutingfeng/balloon_hashing

publish_to: 'none'

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  crypto: ^3.0.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
